### ISSUE TITLE
请问源码是否有问题

### ISSUE THREAD

**Issue by naiximcn** [MrXiaoM/MiraiUtils#1]
### 这是javac CommandListener.java时的截图
![image](https://user-images.githubusercontent.com/87113988/175938853-f8d7a897-91c0-4a05-aa8e-64cc6b54953f.png)

**Comment by MrXiaoM** [comment]
当时我是用 Eclipse 写的，这个项目我早就废弃了。
看问题指向的位置，似乎全部都是 mirai 的类，请确定已导入 mirai 作为依赖。

**Comment by MrXiaoM** [comment]
？
我忽然缓过神来。
你用javac来编译？
正经人有IDE谁还会去手打javac编译啊

**Comment by MrXiaoM** [comment]
Timeout.

**Comment by naiximcn** [comment]
> 当时我是用 Eclipse 写的，这个项目我早就废弃了。 看问题指向的位置，似乎全部都是 mirai 的类，请确定已导入 mirai 作为依赖。

已经导入了

**Comment by naiximcn** [comment]
> ？ 我忽然缓过神来。 你用javac来编译？ 正经人有IDE谁还会去手打javac编译啊

IDE点Build惹以后没几秒种就显示好惹 打开目录什么也没有www

**Comment by MrXiaoM** [comment]
> IDE点Build惹以后没几秒种就显示好惹 打开目录什么也没有www

跑 buildPlugin 任务啊（）
